import type { Metadata } from 'next'
import Link from 'next/link'
import { ExternalLink } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { summarizeHysa, type HysaRow } from '@/lib/hysa/analytics'

export const metadata: Metadata = { title: 'Admin · Team Hysa' }

// Traffic and ticket demand generated by /hysa (phase 44). Auth + admin
// role are enforced by app/admin/layout.tsx; interactions are admin-readable
// under RLS. Read-only.
export const dynamic = 'force-dynamic'

const DAYS = 90
const PAGE = 1000
const MAX_ROWS = 50_000

async function loadRows(): Promise<{ rows: HysaRow[]; error: string | null }> {
  const supabase = await createClient()
  const since = new Date(Date.now() - DAYS * 86_400_000).toISOString()
  const rows: HysaRow[] = []
  for (let from = 0; from < MAX_ROWS; from += PAGE) {
    const { data, error } = await supabase
      .from('interactions')
      .select('type, session_id, utm_source, utm_medium, utm_campaign, referrer, platform, metadata, created_at, path')
      .like('path', '/hysa%')
      .gte('created_at', since)
      .order('created_at', { ascending: true })
      .range(from, from + PAGE - 1)
    if (error) return { rows, error: error.message }
    rows.push(...((data ?? []) as HysaRow[]))
    if (!data || data.length < PAGE) break
  }
  return { rows, error: null }
}

const pct = (n: number) => `${(n * 100).toFixed(1)}%`

function Bar({ label, value, max, sub }: { label: string; value: number; max: number; sub?: string }) {
  return (
    <div className="flex items-center gap-3 text-sm">
      <span className="w-36 flex-shrink-0 truncate text-white/80" title={label}>
        {label}
      </span>
      <span className="relative h-2.5 flex-1 overflow-hidden rounded-full bg-white/[0.06]">
        <span className="absolute inset-y-0 left-0 rounded-full bg-flame-500" style={{ width: `${max ? (value / max) * 100 : 0}%` }} />
      </span>
      <span className="w-24 flex-shrink-0 text-right tabular-nums text-white">
        {value}
        {sub && <span className="ml-1 text-xs text-white/45">{sub}</span>}
      </span>
    </div>
  )
}

function Card({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
      <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-white/50">{title}</h2>
      <div className="mt-4 space-y-2.5">{children}</div>
    </section>
  )
}

export default async function HysaAnalyticsPage() {
  const { rows, error } = await loadRows()
  const s = summarizeHysa(rows)
  const maxDay = Math.max(1, ...s.daily.map((d) => d.visitors))

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold text-white">Team Hysa page</h1>
          <p className="mt-1 text-sm text-white/55">
            Last {DAYS} days · {rows.length} interactions · /hysa, /hysa/de, /hysa/en
          </p>
        </div>
        <Link href="/hysa" target="_blank" className="inline-flex items-center gap-1.5 text-sm text-flame-200 hover:underline">
          Open page <ExternalLink className="h-3.5 w-3.5" />
        </Link>
      </div>

      {error && (
        <p className="rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-100">Could not load all data: {error}</p>
      )}

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        {[
          { label: 'Unique visitors', value: String(s.visitors) },
          { label: 'Page views', value: String(s.pageViews) },
          { label: 'Ticket clicks', value: String(s.ticketClicks) },
          { label: 'Visitors who clicked', value: String(s.clickers) },
          { label: 'Click-through rate', value: s.visitors ? pct(s.ctr) : '—' },
        ].map((k) => (
          <div key={k.label} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
            <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-white/45">{k.label}</p>
            <p className="mt-1 text-3xl font-semibold tabular-nums text-white">{k.value}</p>
          </div>
        ))}
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card title="Daily — unique visitors (clicks)">
          {s.daily.length === 0 && <p className="text-sm text-white/45">No visits yet.</p>}
          {s.daily.map((d) => (
            <Bar key={d.day} label={d.day} value={d.visitors} max={maxDay} sub={`(${d.clicks})`} />
          ))}
        </Card>

        <Card title="Traffic sources — visitors · CTR">
          {s.sources.length === 0 && <p className="text-sm text-white/45">No visits yet.</p>}
          {s.sources.map((src) => (
            <Bar
              key={src.source}
              label={src.source}
              value={src.visitors}
              max={s.sources[0]?.visitors ?? 1}
              sub={src.visitors ? pct(src.clickers / src.visitors) : ''}
            />
          ))}
        </Card>

        <Card title="Category clicks (views)">
          {s.categories.map((cat) => (
            <Bar
              key={cat.category}
              label={cat.category.toUpperCase()}
              value={cat.clicks}
              max={Math.max(1, ...s.categories.map((x) => x.clicks))}
              sub={`(${cat.views})`}
            />
          ))}
        </Card>

        <Card title="Language — visitors">
          {s.languages.map((l) => (
            <Bar key={l.lang} label={l.lang === 'sq' ? 'Shqip' : l.lang === 'de' ? 'Deutsch' : l.lang === 'en' ? 'English' : l.lang} value={l.visitors} max={Math.max(1, ...s.languages.map((x) => x.visitors))} />
          ))}
          <p className="pt-1 text-xs text-white/45">Language switches: {s.languageChanges}</p>
        </Card>

        <Card title="Ticket clicks by button">
          {s.clickTypes.map((t) => (
            <Bar key={t.type} label={t.type} value={t.count} max={Math.max(1, ...s.clickTypes.map((x) => x.count))} />
          ))}
        </Card>

        <Card title="Shares">
          {s.shares.map((t) => (
            <Bar key={t.type} label={t.type} value={t.count} max={Math.max(1, ...s.shares.map((x) => x.count))} />
          ))}
        </Card>
      </div>

      <Card title="Campaigns (utm_source / medium / campaign / content) — visitors · clicks">
        {s.campaigns.length === 0 && <p className="text-sm text-white/45">No UTM-tagged visits yet.</p>}
        <div className="overflow-x-auto">
          <table className="w-full min-w-[560px] text-left text-sm">
            <thead className="text-[11px] uppercase tracking-[0.12em] text-white/45">
              <tr>
                <th className="py-1.5 pr-3 font-semibold">Source</th>
                <th className="py-1.5 pr-3 font-semibold">Medium</th>
                <th className="py-1.5 pr-3 font-semibold">Campaign</th>
                <th className="py-1.5 pr-3 font-semibold">Content</th>
                <th className="py-1.5 pr-3 text-right font-semibold">Visitors</th>
                <th className="py-1.5 text-right font-semibold">Clicks</th>
              </tr>
            </thead>
            <tbody className="text-white/80">
              {s.campaigns.map((cmp) => (
                <tr key={cmp.key} className="border-t border-white/[0.06]">
                  <td className="py-1.5 pr-3">{cmp.source}</td>
                  <td className="py-1.5 pr-3">{cmp.medium}</td>
                  <td className="py-1.5 pr-3">{cmp.campaign}</td>
                  <td className="py-1.5 pr-3">{cmp.content}</td>
                  <td className="py-1.5 pr-3 text-right tabular-nums">{cmp.visitors}</td>
                  <td className="py-1.5 text-right tabular-nums">{cmp.clicks}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <p className="text-xs text-white/40">
        Visitors = anonymous browser sessions (no cookies, no IP). Ticket clicks = clicks into the official Nelson Hysa ticket channel; purchases
        happen there and aren&apos;t visible to AlbaGo. Tag links like <code>/hysa?utm_source=nelson_hysa&amp;utm_medium=instagram&amp;utm_campaign=duesseldorf</code>.
      </p>
    </div>
  )
}
